# Generated by Django 5.0.1 on 2024-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='back_content',
            new_name='meaning',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='front_content',
            new_name='word',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='rounds_seen',
            field=models.JSONField(default=dict),
        ),
    ]
